PLATFORM_A:      # ALZURA2025-2.csv
  nom_reference: "productReference"
  quantite_stock: "Stock"

PLATFORM_B:      # departo.csv
  nom_reference:  "interne Artikelnummer" #" Teilenummer "
  quantite_stock: "Zustand"  # "Vergleichs-Teilenummern"

PLATFORM_C:      # Market-DE-NEW (1) (1).csv
  nom_reference: "article_nr"
  quantite_stock: "quantity"

PLATFORM_D:      # 07zr2026.csv
  nom_reference: "ProductReference"
  quantite_stock: "Stock"

PLATFORM_E:      # Ajout offre drox auto  (2).xlsx
  nom_reference: "ID Produit"
  quantite_stock: "Quantité Offre"

PLATFORM_F:      # pieces aftermarket.xlsx
  nom_reference: "reference"
  quantite_stock: "stock"

PLATFORM_G:      # TIELEHABERDER.csv
  nom_reference: "artikelnr"
  quantite_stock: "menge"

